server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.sam.springcloud.entities       #所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://ip:4306/cloudDB01 # 数据库名称
    username: username
    password: pwd
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200  # 等待连接获取的最大超时时间
eureka:
  client: #服务端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001  #这个是在eureka的Status上面显示的名称
    prefer-ip-address: true  #这个是鼠标移动到Status上面的名称时，浏览器左下角显示ip地址，否则默认显示localhost

info:  #点击Status上面的服务名称的时候会显示以下的信息
  app.name: microservicecloud-dept8001
  company.name: com.sam.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
