server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name: sam-microcloud
  company.name: www.sam.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

zuul:
  ignored-services: "*" #忽略所有默认匹配的path。只能路由到我们手动配置的路劲
  prefix: /sam           #配置统一前缀
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
